### ISSUE TITLE
Archived servers are showing

### ISSUE THREAD

**Issue by drbyte** [phppirate/anvil#1]
Decommissioned archived servers are showing in the servers list.

**Comment by phppirate** [comment]
Thank You for your interest in Anvil.
This feature does not seem to be documented yet. I will add it as soon as possible.

**Comment by drbyte** [comment]
Apparently it's the `revoked` key that indicates it's archived:

https://github.com/themsaid/forge-sdk/issues/15#issuecomment-298019649

**Comment by phppirate** [comment]
Perfect. Will add a filter to clear out revoked servers.
    
  
  
Thank You,
  Sam Podlogar   
sam@podlogar.com
  
  
  
  
  

  
  
>

**Comment by phppirate** [comment]
https://www.dropbox.com/s/l8hhyzdc266ck1w/Filter%20Revoked%20Servers.zip?dl=0
@drbyte Can you try this version of the app and see if the "Show Archived Servers" button at the bottom of the servers window actually works. I do not have any archived/revoked servers so I cannot test this.

**Comment by phppirate** [comment]
Should be fixed in version 0.4-alpha

**Comment by drbyte** [comment]
👍
