### ISSUE TITLE
Dark Menu Bar Shows Black Icon

### ISSUE THREAD

**Issue by vmitchell85** [phppirate/anvil#2]
If you have "Use dark menu bar and Dock" checked in System Preferences the icon in the menu bar is still black which makes it hard to see.

<img src="http://i.imgur.com/5THBO6m.png" />

**Comment by phppirate** [comment]
Thank You for pointing this out. Will fix asap! 👍

**Comment by vmitchell85** [comment]
No rush, just figured I'd let you know...

**Comment by phppirate** [comment]
Fixed in v0.4-alpha
