### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by helmerdx** [phppirate/anvil#3]
Can i have different accounts?

**Comment by phppirate** [comment]
Currently, no.
But that feature has just been moved to the top of my todo list.
Expect a release within 2 days.

**Comment by helmerdx** [comment]
Thank you so much

**Comment by helmerdx** [comment]
@phppirate This will be a release? I saw the last commit.

**Comment by phppirate** [comment]
It will be a release. I am in an area with really bad internet so I will upload it when I get to the office tomorrow.

Sam Podlogar
sam@podlogar.com
Mission-4.com

**Comment by phppirate** [comment]
This feature has been added in the latest release v0.7-alpha
